### ISSUE TITLE
Disable default features

### ISSUE THREAD

**Issue by steffahn** [Riey/cargo-feature#16]
There isn’t a way to disable default features (i.e. add `default-features = false`), right?

Maybe we could make it so that `cargo feature crate_name ^default` does that, and/or a new option, e.g. `cargo feature crate_name --disable-default-features` and `cargo feature crate_name --enable-default-features`

**Comment by Riey** [comment]
Sounds great!

I think `^default` may conflict with feature named `default` so I like `disable-default-feature` or some short name

**Comment by steffahn** [comment]
can there even be a feature named “default”?

**Comment by Riey** [comment]
I have no idea but even `default` name is impossible users can be confused because it looks like `default` feature

**Comment by steffahn** [comment]
Tested it, turns out `cfg[feature = "default"]` actually works. The syntax in the cargo.toml, e.g.
```toml
[features]
default = ["ico", "webp"]
bmp = []
png = []
ico = ["bmp", "png"]
webp = []
```
(from [here](https://doc.rust-lang.org/cargo/reference/features.html#the-default-feature))

thus _actually_ talks about a feature called "default" which is enabled by default. So disabling “default features” literally just disables the feature called `default` :D

**Comment by Riey** [comment]
Hmm.. it makes sense I'm forgot about how default feature made

so only difference point is manifest but that doesn't matter a lot then `^default` looks best option

**Comment by steffahn** [comment]
There’s also the option of supporting both `cargo feature crate_name ^default`/`cargo feature crate_name +default` **and** a specialized pair of flags like `[disable/enable]-default-features`. The flags would perhaps also be easier to have properly documented in `--help`.

**Comment by steffahn** [comment]
Hm… on the other hand, I guess mentioning it in the description of `<features>...` should be enough, no need for the overhead of another flag.

Something like an added remark ``This also supports `^default` to disable default features.``

**Comment by Riey** [comment]
> Something like an added remark This also supports `^default` to disable default features.

I think that description can be included in specialized `[disable/enable]-default-features` flag's

**Comment by steffahn** [comment]
> I think that description can be included in specialized `[disable/enable]-default-features` flag's

Sure, that seems decent, too.

**Comment by Riey** [comment]
> the fact that options come before the crate name and features come after makes a --disable-default-features flag somewhat misplaced, too. Edit: Maybe the command line arguments are more flexible than I thought and don’t actually care if you put additional options at the end…

Structopt already parse flag in the end position

**Comment by steffahn** [comment]
Wow, you’re quick
