### ISSUE TITLE
Unknown command: e

### ISSUE THREAD

**Issue by SirWindfield** [Riey/cargo-feature#4]
Given the following input: `cargo feature serde derive` I get this panic:
```
thread 'main' panicked at 'Unknown command: e', C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-feature-0.3.0\src\main.rs:91:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I have two "complains" about this:
1) The syntax should be denoted in the `--help` description. There is no mention of the `b/n` syntax.
2) Please no panics! I think a better approach is to check if the value if feature starts with n/b and if not, use `eprintln` to print an error message and exit the program.

**Comment by Riey** [comment]
Thanks for detailed advise! I just fix it and add more help text
