### ISSUE TITLE
More intuitive syntax

### ISSUE THREAD

**Issue by SirWindfield** [Riey/cargo-feature#5]
Slight follow-up on #4:

What do you think about using a more intuitive way to define feature flags?
These are the same. Note that the default checks for serde inside of `dependencies`:
```
$ cargo feature serde derive
$ cargo feature serde +derive
```
This removes it:
```
$ cargo feature serde -derive
```

Passing the `--build,-b` flag does the same for build dependencies:
```
$ cargo feature serde derive --build
$ cargo feature serde -derive -b
```

Alongside this, `--dev,-d` could be used for development dependencies.

**Comment by Riey** [comment]
Well, I just made now syntax using type flag

```
$ cargo feature serde -t build +derive
```

--normal flag is also good but I think it's good to target one crate at a time
0.3.0 was not very good in that regard
