### ISSUE TITLE
Optional dependencies do not work

### ISSUE THREAD

**Issue by SirWindfield** [Riey/cargo-feature#7]
I am on the newest version. It seems like a fix has already been merged (#3) but it doesn't work properly. Given this `Cargo.toml`:
```toml
[dependencies]
serde = { version = "1.0.114", optional = true }
```

Running `cargo feature serde +derive` panics:
```text
$ cargo feature serde +derive
thread 'main' panicked at 'Get package metadata', src\libcore\option.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I'd expect it to modify the file like this:
```toml
[dependencies]
serde = { version = "1.0.114", optional = true, features = ["derive"] }
```

**Comment by Riey** [comment]
Sorry I can't reproduce your issue would you like to try a new version?

**Comment by Riey** [comment]
If you still have problem please reopen this
